language: python

matrix:
  fast_finish: true

python:
  - 3.7

services: docker

env:
  global:
    - LIVELINESS_TIMEOUT=300
    - OAREPO_ADMIN_PASSWORD=Tr4vi1SWasH3r3!
    - OAREPO_ADMIN_USER=admin@oarepo.org
    - OAREPO_APP_ALLOWED_HOSTS=frontend,localhost,127.0.1.1
    - INVENIO_SEARCH_ELASTIC_HOSTS='es:9200'
    - INVENIO_SECRET_KEY=This1SSoooS3cr#t
    - INVENIO_WSGI_PROXIES=2
    - INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://oarepo:oarepo@db/oarepo
    - INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/
    - INVENIO_CACHE_TYPE=redis
    - INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1
    - INVENIO_CACHE_REDIS_URL=redis://cache:6379/0
    - INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3
    - INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/
    - INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2
    - INVENIO_CELERY_LOG_LEVEL=INFO
    - INVENIO_SERVER_NAME=127.0.0.1:5001
    - INVENIO_JSONSCHEMAS_HOST=cesnet.cz
    - INVENIO_SEARCH_INDEX_PREFIX=oarepo-
    - INVENIO_APPLICATION_ROOT=/api

  matrix:
    - OAREPO_VERSION=3.2.1 OAREPO_ES_VERSION=es7
    - OAREPO_VERSION=3.3.0 OAREPO_ES_VERSION=es7

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
  - docker-compose -f docker-compose.deploy.yml build
  - docker-compose -f docker-compose.full.yml build
  - docker-compose -f docker-compose.full.yml up --no-start

script:
  - docker-compose -f docker-compose.deploy.yml up --abort-on-container-exit
  - docker-compose start
  - docker ps
  - docker-compose stop
  - docker-compose -f docker-compose.full.yml start
  - docker ps
  - timeout ${LIVELINESS_TIMEOUT} bash -c 'while [[ "$(curl -k -sf -o /dev/null -w ''%{http_code}'' https://localhost/.well-known/heartbeat/liveliness)" != "200" ]]; do docker ps; sleep 5; done'
  - docker-compose -f docker-compose.full.yml stop
