# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# Oarepo Docker is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# Backend services for needed for development.
#
# Usage::
#
#   $ docker-compose up -d
#   $ ./conf/wait-for-services.sh
#
# Following services are included:
# - Cache: Redis (exposed port: 6379)
# - DB: (PostgresSQL/MySQL) (exposed port: 5432 or 3306)
# - Message queue: RabbitMQ (exposed ports: 5672, 15672)
# - Elasticsearch (exposed ports: 9200, 9300)
#
version: '2.3'
volumes:
  archived_data:
  uploaded_data:
  static_data:
services:
  deploy-oarepo:
    user: root
    extends:
      file: docker-services.yml
      service: app
    command: [ "deploy" ]
    image: "oarepo-base:${OAREPO_VERSION}-${OAREPO_ES_VERSION}"
#    ports:
#      - "5000"
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
      - static_data:/opt/invenio/var/instance/static
    links:
      - cache
      - es
      - mq
      - db
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es7
